language: node_js
node_js:
  - "11.15"
cache: 
  yarn: true
  
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH

before_install: 
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  #build runner
  - yarn run bootstrap
before_deploy: 
  - "echo cacio"
  - yarn run build
  - chmod +x buildpath.sh
  - . ./buildpath.sh
  - ls -latr
jobs:
  include:
    # - stage: test
    #   script: yarn run test
    #  - stage: build
    #     script: echo "CACIOOOOOOOOOOOOOOOOOOOOOOO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    #     if: branch != master 
     - stage: deploy ui
        deploy: 
        
        #provider: script
        #script: npm whoami && yarn run release
        # provider: npm
        # email: "${NPM_EMAIL}"
        # api_key: "${NPM_TOKEN}"
        # skip_cleanup: true
        # on: 
        #   tags: true
        #   condition: "$TRAVIS_TAG =~ ^@grimtim/prova"
        provider: firebase
          token:
            secure: $FIREBASE_TOKEN