language: node_js
node_js:
  - "11.15"
cache: 
  yarn: true
  
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH

before_install: 
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  

install:
  - cp npm.release $HOME/.npmrc
  - npm whoami
  #build runner
  - yarn run bootstrap

jobs:
  include:
    # - stage: test
    #   script: yarn run test
    # - stage: build
    #   script: yarn run build 
    - stage: deploy ui
      deploy: 
        provider: script
        script: npm whoami && yarn run release && npm publish build
        skip_cleanup: true
        # on: 
        #   tags: true
        #   condition: "$TRAVIS_TAG =~ ^@grimtim/prova"
      

